
spring.application.name=myapp
server.error.whitelabel.enabled=false
server.error.path=/error

# Configurações do Servidor
server.port=8080

# Configurações do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.root=INFO
